### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by behDev** [jadijadi/bestoon#106]
Hi, i run `python manage.py migrat` and get error:

`Traceback (most recent call last):`
  `File "/home/behzad/bestoon/manage.py", line 22, in <module>`
`    execute_from_command_line(sys.argv)`
`  File "/home/behzad/bestoon/build/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in ``execute_from_command_line`
`    utility.execute()`
`  File "/home/behzad/bestoon/build/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute`
`    django.setup()`
`  File "/home/behzad/bestoon/build/lib/python3.9/site-packages/django/__init__.py", line 24, in setup`
`    apps.populate(settings.INSTALLED_APPS)`
`  File "/home/behzad/bestoon/build/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate`
`    app_config.import_models()`
`  File "/home/behzad/bestoon/build/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models`
`    self.models_module = import_module(models_module_name)`
`  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module`
`    return _bootstrap._gcd_import(name[level:], package, level)`
`  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import`
`  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked`
`  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked`
`  File "<frozen importlib._bootstrap_external>", line 850, in exec_module`
`  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed`
`  File "/home/behzad/bestoon/web/models.py", line 31, in <module>`
`    class Expense(models.Model):`
`  File "/home/behzad/bestoon/web/models.py", line 35, in Expense`
`    user = models.ForeignKey(User)`
`TypeError: __init__() missing 1 required positional argument: 'on_delete'`

Of course, since I did not have Python 2, I used Python 3, does it not cause a problem?

**Comment by mamadinit** [comment]
Hi
In the web/models.py file  edit lines 35 and 45 models.ForeignKey(User)  to models.ForeignKey(User, on_delete=models.CASCADE)
