### ISSUE TITLE
نصب و راه اندازی

### ISSUE THREAD

**Issue by voltan** [jadijadi/bestoon#11]
سلام

من با توسعه پایتون هیچ آشنایی ندارم ، این پروژه رو دیدم و به نظرم رسید فرصت خوبیه که یکم پایتون یاد بگیرم. ممکنه یه داکیومنت چیزی از راهنمای نصب بگذاریم ( من فدورا دارم ) ، و احتمالا با  https://www.jetbrains.com/pycharm برای کد نویسی و تست کار کنم

**Comment by jadijadi** [comment]
fixed
