### ISSUE TITLE
مشکل فونت در کلاینت موبایل

### ISSUE THREAD

**Issue by bobsilon** [jadijadi/bestoon#21]
سلام، فونت برای بقیه هم اینطوری هستش؟
![image](https://cloud.githubusercontent.com/assets/2111724/21798155/38261a2c-d728-11e6-9500-089cf05b6706.png)

مثل اینکه فونت وزیر اضافه شده به سیستم، اما چرا متن ها با این فونت نشون داده نمیشن؟

**Comment by bobsilon** [comment]
&rlm;
اوه مثل اینکه مشکل تو فایل [style.css](https://github.com/jadijadi/bestoon/blob/master/clients/ionic/bestoon/www/css/style.css#L22) بوده. تو خط ۲۲ یه اشتباه کوچیک آدرس دهی هستش. همین الان یه پول ریکوئست زدم واسه این، اما به نظرم بهتر باشه که با scss و استانداردتر انجام بشه.
&lrm;

**Comment by jadijadi** [comment]
این رو باید با چیزی مثل 
STATIC_URL = '/static/'

در تنظیمات حل کنی. می گه فایل های استاتیک از کجا لود بشن. همچنین به 
python manage.py collectstatic
هم نگاه کن

**Comment by bobsilon** [comment]
STATIC_URL ?
کجاس؟ سمت سرورم زیاد خوب نیست :دی

**Comment by jadijadi** [comment]
فایل تنظیمات. خب دقیقا دو تا کلمه کلیدی رو دادم که بخونی دیگه (: قرا رنیست
خوب باشه قراره خوب بشه (:

**Comment by bobsilon** [comment]
درسته ولی خوب مگه 
STATIC_URL 
ماله جنگو نیست؟ ارتباطش رو با ایونیک نمیفهمم

**Comment by jadijadi** [comment]
اوه.. راست می گی ها (: اشتباه و بی دقتی از من بود.
ولی.. بذار برم چک کنم کدها و اپ رو. ای پی کی فکر کنم کار میکنه به خوبی. تست
می کنم می گم.

**Comment by jaavid** [comment]
روش درست تغییر استایل توی آیونیک اینه که [طبق پیشنهاد خودشون](http://ionicframework.com/docs/cli/sass.html) از 
sass 
استفاده کنیم و بزاریم فایل سی اس اس نهایی رو خود آیونیک تولید کنه.

استفاده ازش هم ساده س، فقط کافیه که داخل پروژه آیونیک
 ionic setup sass
رو اجرا کنیم، آیونیک یه فایل سس به ما میده و با هر بار سرو کردن پروژه سی اس اس ما رو بر اساس اون فایل تغییر میده.

**Comment by bobsilon** [comment]
&rlm; 
@jadijadi 
یه چیزی هم هست، اونم اینکه اگه از قبل این فونت رو سیستم نصب باشه، اون رو میخونه. ولی اگه یکی مثل من فونت وزیر رو نصب نداشته باشه، مثل عکسی که بالا گذاشتم میشه.
 &lrm;

**Comment by jadijadi** [comment]
تشکر از توضیحات.
