### ISSUE TITLE
مشکل در استفاده ازتابع یونیکد در فایل مدلز

### ISSUE THREAD

**Issue by mrt-kousha** [jadijadi/bestoon#42]
زمانی که یاد دادین این تابع باعث میشه به جای اسم مدل هایی که تعریف میکنیم اسمی که میخوایم رو داخل پنل ادمین برمیگردونه برای من تغییری ایجاد نمیشد. گفتم راه حلش رو اینجا هم بگم شاید مشکل کس دیگری هم بوده باشه
به جای تعریف کردن
def _ _unicode_ _(self):
از 
def _ _str_ _(self):
استفاده کردم

ممنون از آموزش خوبتون.

**Comment by jadijadi** [comment]
خیلی هم عالی. البته این وابسته به پایتون ۲ و ۳ است (: خودش جلوش با کامنت
توضیح داده که در هر پایتون باید کدوم رو بزنیم. اما خوبه اینجا هم گفتی چون
شاید به درد یکی بخوره
