### ISSUE TITLE
PMMailمشکل در استفاده از  

### ISSUE THREAD

**Issue by alishb94** [jadijadi/bestoon#51]
خودمون رو داشته باشیم تا صفحه رجیستر بتونه کار کنه ؟POSTMARK_API_TOKEN  چطور میشه

**Comment by Reshad1983** [comment]
کاری که من کردم این بود که به سایت postmarkapp رفتم و یه اکانت درست کردم
بعد از وارد شدن دمین سایتم رو ثبت و وریفای کردم
بعد اسم سرور رو ثبت کردم که همانجا بهم توکن رو داد
