### ISSUE TITLE
اضافه کردن قابلیت های جدید

### ISSUE THREAD

**Issue by arfprogrammer** [jadijadi/bestoon#84]
سلام
تو این ورژن تا الان چند تا قابلیت اضاف کردم
۱- برای استفاده و اجراکردن پروژه در پلتفرم فندوق فایل fandogh.yml رو به پروژه اضافه کردم
۲- سورس پروژه رو برای جنگو ورژن ۲ تغییر دادم
۳- از گوگل کپچا ورژن ۳ در سایت استفاده شده
۴- برای ارسال ایمیل از سرویس سایت zoho استفاده کردم. کمی تنظیمات لازم داشت که همه چیزش روشن و شفاف است و پس از کانفیگ کردن ایمیل ارسال ایمیل رو ازطریق stmp انجام دادم
۵- در سایت از سرویس رایچت استفاده کردم که سرویس جالبی در رابطه با ارتباط چت با مشتری هست  و پیشنهاد میکنم کسایی که لازم دارن ازش استفاده کنن
۶- مورد آخر برای راه اندازی این سایت در سرویس فندوق فولدر static رو در روت پروژه کپی کنین

**Comment by arfprogrammer** [comment]
سایت الان ازطریق لینک زیر در دسترس هستش

**Comment by mhkarimi1383** [comment]
پس اگه میشه به پول ریکویستهای https://github.com/jadijadi/bestoon/pull/79 و https://github.com/jadijadi/bestoon/pull/80 و https://github.com/jadijadi/bestoon/pull/77 یه نگاهی بندازید و روی اونی که سمت خودتون بالاست روی سایت اعمال کنید که کاملتر بشه

**Comment by arfprogrammer** [comment]
چشم حتما تو اولین فرصت انجامش میدم

**Comment by mhkarimi1383** [comment]
default backend - 404
این ارور روی صفحه اصلی میاد این رو هم لطفا حل کنید

**Comment by arfprogrammer** [comment]
لطف می کنی حالتی که این اتفاق رخ میده رو بیشتر توضیح بدی؟ چون تستش رو کامل انجام داده بودم

**Comment by mhkarimi1383** [comment]
مشکل از سمت سرور هستش حتما سرور اومده پایین

**Comment by arfprogrammer** [comment]
بله دیدم سرور رو دوباره راه اندازی می کنم

**Comment by BaseMax** [comment]
**rayakade.ir uses an invalid security certificate.**

```
The certificate is not trusted because it is self-signed.
 
Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT
```
 
default backend - 404

**Comment by arfprogrammer** [comment]
سلام
باتوجه به اینکه من سایت رو روی نسخه رایگان سرویس ابری فندوق بالا اورده ام هر از چند وقت کلا سرویس زمان عمرش پایان می یابد و مجددا باید اون رو از نو فعال سازم و از این به بعد سعی میکنم این کار رو هفته ای چک نمایم تا سرویس همیشه بالا باشد
با تشکر از شما

**Comment by arfprogrammer** [comment]
> **rayakade.ir uses an invalid security certificate.**
> 
> ```
> The certificate is not trusted because it is self-signed.
>  
> Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT
> ```
> 
> default backend - 404

fixed, thanks

**Comment by mhkarimi1383** [comment]
salam error SMTP while singing-up

**Comment by BaseMax** [comment]
> salam error SMTP while singing-up

True,

```
Request Method: | POST
-- | --
http://rayakade.ir/accounts/register
3.1.5
SMTPAuthenticationError
(535, b'Authentication Failed')
/usr/local/lib/python3.7/smtplib.py, line 642, in auth
/usr/local/bin/python
3.7.9
['/usr/src/app',  '/usr/local/bin',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
Thu, 21 Jan 2021 15:52:55 +0000
```

### Logs
```
Environment:


Request Method: POST
Request URL: http://rayakade.ir/accounts/register

Django Version: 3.1.5
Python Version: 3.7.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'snowpenguin.django.recaptcha3',
 'web']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/app/web/views.py", line 96, in register
    , 'info@rayakade.ir', [email], fail_silently = False)
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/usr/local/lib/python3.7/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/local/lib/python3.7/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/local/lib/python3.7/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)

Exception Type: SMTPAuthenticationError at /accounts/register
Exception Value: (535, b'Authentication Failed')
```

**Comment by mhkarimi1383** [comment]
@arfprogrammer Please solve it
